function IPE481attendance = importfile_attendance_file(workbookFile, sheetName, dataLines)
%IMPORTFILE1 Import data from a spreadsheet
%  IPE481ATTENDANCE = IMPORTFILE1(FILE) reads data from the first
%  worksheet in the Microsoft Excel spreadsheet file named FILE.
%  Returns the data as a table.
%
%  IPE481ATTENDANCE = IMPORTFILE1(FILE, SHEET) reads from the specified
%  worksheet.
%
%  IPE481ATTENDANCE = IMPORTFILE1(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  IPE481attendance = importfile1("C:\Users\nazmul\Documents\MATLAB\IPE 481 attendance 25.08.2020.xlsx", "meetingAttendanceList (4)", [2, 218]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 25-Aug-2020 17:17:23

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, 10000];
end

%% Setup the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 1);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":A" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = "Attendees";
opts.VariableTypes = "string";

% Specify variable properties
opts = setvaropts(opts, "Attendees", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "Attendees", "EmptyFieldRule", "auto");

% Import the data
IPE481attendance = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":A" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    IPE481attendance = [IPE481attendance; tb]; %#ok<AGROW>
end

end